export const examples = [
	["diff(fn(x) { x })(3)"],
	["diff(fn(x) { 2 })(3)"],
	["diff(fn(x) { 2 * x })(3)"],
	["diff(fn(x) { (2 + 0) * x })(3)"],
	["let second = 2; diff(fn(x) { x ** second })(3)"],
	["diff(fn(x) { 3 * x ** 2 })(3)"],
	["diff(fn(x) { 2 + 2 })(3)"],
	["diff(fn(x) { 2 + x })(3)"],
	["diff(fn(x) { 2 * x ** 3 + x + 3 })(3)"],
	["diff(fn(x) { 2 * x ** 3 + (x + 3) })(3)"],
	["diff(fn(x) { 2 * x ** 3 + x + 3 + 4 * x + 5 * x ** 4 })(3)"],
	["let f = fn(y) { y }; diff(fn(x) { x ** 7 + f(2) })(3)"],
	["let f = fn(y) { y }; diff(fn(x) { x ** 7 + f(x) })(3)"],
	["let second = 2; diff(fn(x) { x ** 7 + second })(3)"],
	["diff(fn(x) { 2 * x ** 3 - (x + 3) })(3)"],
	["diff(fn(x) { (x + 2 * x ** 3) * (x + 1) })(3)"],
	[
		"diff(fn(x) { (x + 2 * x ** 3) * (x + 1) + (x + 3 * x ** 3) * (x + 1)  })(3)",
	],
	["diff(fn(x) { (x + 2 * x ** 3) / (x + 1) })(3)"],
	[
		"diff(fn(x) { (x + 2 * x ** 3) / (x + 1) + (x + 3 * x ** 3) / (x + 1)  })(3)",
	],
	["diff(fn (x) { (3 * x ** 2 + 5 * x) ** 4 })(3)"],
	["diff(fn (x) { 1 / (2 * x + 3) })(3)"],
	["sin(0)"],
	["sin(pi() / 2)"],
	["cos(0)"],
	["cos(pi() / 2)"],
	["tan(0)"],
	["tan(pi() / 4)"],
	["ln(0)"],
	["ln(1)"],
	["ln(e())"],
	["exp(e())"],
	["exp(1)"],
	["ln(exp(3))"],
	["diff(fn(x) {sin(x)})(0)"],
	["diff(fn(x) {sin(x)})(pi() / 2)"],
	["diff(fn(x) {cos(x)})(0)"],
	["diff(fn(x) {cos(x)})(pi() / 2)"],
	["diff(fn(x) {tan(x)})(0)"],
	["diff(fn(x) {tan(x)})(pi() / 4)"],
];
